name = "silver fiesta"
author = "snorps"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab11a12ea16a2338eceb36328bc868520904ceeff74ae5ac447934da935e6e89"

[versions]
forge = "45.1.0"
minecraft = "1.19"
