name = "silver fiesta"
author = "snorps"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf486edd28c0eb056a70391802c3baf15c41ada2663bf61d72061f5c79d76a9b"

[versions]
forge = "45.1.0"
minecraft = "1.19"
