name = "silver fiesta"
author = "snorps"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bda2d190c892e96b0424f06165a37a0c6537bcbdcd4e6cfc2c8967efebd369cb"

[versions]
forge = "45.1.0"
minecraft = "1.19"
