name = "silver fiesta"
author = "snorps"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a29d00c5e2f188d03b8b49c1376a575eaba1290e7ed18aa4e13f2ca13e8f4a13"

[versions]
forge = "45.1.0"
minecraft = "1.19"
