name = "silver fiesta"
author = "snorps"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11303f5cce642850b525f2c9dbbb455877b6757c5ea594013cee4d661d0da2d1"

[versions]
forge = "45.1.0"
minecraft = "1.19"
