name: deploy-development
run-name: ${{ github.actor }} is deploying to remote.
on: 
  push:
    branches: 
      - main
jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - run : rm -rf ~/www/html/snorpsnet/silver-fiesta/pack
      - run: git clone --branch main git@github.com:Snorps/silver-fiesta.git ~/www/html/snorpsnet/silver-fiesta/pack